name: Create Resource Pack BW v1
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    
      - name: GitHub Tag Name example
        run: |
          echo "======================================================"
          echo "github.ref_name: ${{  github.ref_name }}"
          echo "======================================================"
          echo "github.run_id: ${{  github.run_id }}"
          echo "======================================================"
          echo "github.run_number: ${{  github.run_number }}"
          echo "======================================================"
          echo "github.run_attempt: ${{  github.run_attempt }}"
          echo "======================================================"
          
         
      - uses: actions/checkout@v3

      - uses: actions/create-release@v1.1.4
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: "ProjectBW_Fonts"
          draft: false
          prerelease: false
          
      - uses: ksm2/archive-action@v1
        id: archive
        with:
          root-directory: resource_pack  
          format: "zip"
          name: ProjectBW_Fonts
                
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.archive.outputs.path }}
          asset_name: ${{ steps.archive.outputs.name }}
          asset_content_type: ${{ steps.archive.outputs.media-type }}

      - uses: robinraju/release-downloader@v1.9
        with:
          latest: true
          fileName: "ProjectBW_Fonts.zip"
          out-file-path: "upload"

      - uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          #local-dir: ${{ steps.archive.outputs.path }}/
          local-dir: '/home/runner/work/resource_pack/resource_pack/upload/'
          #server-dir: ${{ secrets.FTP_PATH }}/
          server-dir: /var/lib/pterodactyl/volumes/8eca4a8a-9337-4709-87f6-9a622d31795f/plugins/forcepack/packs/
          protocol: ftp
          security: loose
          log-level: verbose
          port: 21 # todo replace with your web hosts ftps port
